//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ComponentBase } from '../General/ComponentBase.model';

export class EntitySelector extends ComponentBase
{
	public EntityName: string;
	public DisplayAttributes: string[];
	public KeyAttributes: string[];
	public RelationAttributes: string[];
}
