//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityListAttribute } from './EntityListAttribute.model';

export class EntityList
{
	public Entities: any[];
	public Attributes: EntityListAttribute[];
}
