//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityComponentBase } from './EntityComponentBase.model';
import { EntityListAttribute } from './EntityListAttribute.model';
import { RelationAttributeDto } from './RelationAttributeDto.model';

export class EntityList extends EntityComponentBase
{
	public Entities: any[];
	public Attributes: EntityListAttribute[];
	public RelationAttributes: RelationAttributeDto[];
}
