//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export class AttributeMetadata
{
	public IsKey: boolean;
	public IsRelationKey: boolean;
	public AttributeType: any;
}
