//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { MetadataBase } from './MetadataBase.model';

export class AttributeMetadata extends MetadataBase
{
	public IsKey: boolean;
	public AttributeType: any;
}
