//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { MetadataBase } from './MetadataBase.model';
import { AttributeMetadata } from './AttributeMetadata.model';
import { RelationMetadata } from './RelationMetadata.model';

export class EntityMetadata extends MetadataBase
{
	public Attributes: AttributeMetadata[];
	public Relations: RelationMetadata[];
	public RelationInfos: any[];
}
