//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { MetadataBase } from './MetadataBase.model';
import { AttributeMetadata } from './AttributeMetadata.model';
import { EntityMetadata } from './EntityMetadata.model';

export class RelationMetadata extends MetadataBase
{
	public Keys: AttributeMetadata[];
	public AttributeName: string;
	public Entity: EntityMetadata;
	public RelationType: number;
}
