//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityMetadata } from './EntityMetadata.model';
import { AttributeMetadata } from './AttributeMetadata.model';

export class RelationMetadata
{
	public Entity: EntityMetadata;
	public EntityReferenceAttribute: any;
	public Keys: AttributeMetadata[];
	public RelationType: number;
	public IsReference: boolean;
}
