//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ComponentType } from './ComponentType.enum';
import { ComponentBinding } from './ComponentBinding.model';

export abstract class ComponentBase
{
	public Caption: string;
	public Type: ComponentType;
	public Binding: ComponentBinding;
}
