//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityDetail } from '../../../Components/Entities/EntityDetail.model';

export class GetEntityDetailResult
{
	public EntityDetail: EntityDetail;
}
