//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { ComponentBase } from '../General/ComponentBase.model';

export abstract class EditorBase extends ComponentBase
{
	public IsReadOnly: boolean;
}
