//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityParamsBase } from './EntityParamsBase.model';
import { AttributeValue } from '../AttributeValue.model';

export class GetEntityDetailParams extends EntityParamsBase
{
	public Keys: AttributeValue[];
}
