//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityList } from '../../../Components/Entities/EntityList.model';

export class GetEntityListResult
{
	public EntityList: EntityList;
}
