//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

import { EntityMetadata } from './EntityMetadata.model';

export class RelationMetadata
{
	public Entity: EntityMetadata;
	public EntityReferenceAttribute: any;
	public Attributes: any[];
	public IsComposition: boolean;
	public RelationType: number;
	public IsReference: boolean;
}
