//     This code was generated by a Reinforced.Typings tool. 
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.

export enum ComponentType { 
	TextBox = 0, 
	EntitySelector = 1, 
	EntityList = 2
}
